### ISSUE TITLE
.gitignore  is missing after truffle unbox

### ISSUE THREAD

**Issue by natashka894** [Azure-Samples/Blockchain-Ethereum-Template#5]
Could you please remove **.gitignore** from **ignore** section in **truffle-box.json**.

![image](https://user-images.githubusercontent.com/38684870/56730520-dfc10100-6760-11e9-9740-b087815d6d27.png)

**Comment by caleteeter** [comment]
Sorry about that will do

**Comment by caleteeter** [comment]
Done via #6
